research_task:
  # description of the task will be built from one of the prompt templates
  expected_output: >
    A list with 8 bullet points of the most relevant information

final_analysis:
  # description of the task will be built from one of the prompt templates
  expected_output: >
    A list of 5 results
